### ISSUE TITLE
八中版和基准板的区别整理

### ISSUE THREAD

**Issue by ben7th** [mindpin/beikong-eshare#74]
### admin 部分
1. 整个UI布局方面，八中版的好一些
2. 八中版的顶部导航多了一个课程中心
3. 八中版的顶部导航多了一个课程搜索
4. 八中多了一个数据汇总页面（在“首页”的左道航项里）
5. 用户管理是一样的
6. 八中版多出了一个用户分组功能（还蛮复杂的）
7. 八中版多出了一个科目管理（课程单层分类管理）

### manager 部分

基准版的 admin 部分功能在 八中版中属于 manager 角色

1. 基准版的课程管理功能，对应到八中版中，被拆分成两个功能：老师的课程申报和教务管理的课程审批
2. 基准版有选课管理，八中版没有（后来剔掉了）
3. 教师评价没有变化
4. 八中版多一个公告发布功能
5. 八中版多出六个统计功能

**Comment by ben7th** [comment]
3月10号先比较admin部分，剩下的隔天继续。
最后需要整理成表格。

**Comment by arlyxiao** [comment]
Teacher - 老师方面：
两者都有的
1, 问答
2, 基准版导航：个人 = 八中版导航：好友关注
3，动态

八中独有的
1, 课程申报
2, 课程编排
3, 上传课件
4, 课程中心
5, 布置作业
6, 检查作业
7, 文件共享
8, 发布公告
9, 查看公告
10, 我的班级
11, 统计信息

问答具体一些分支功能
12, 提出的问题
13, 得到的解答 
14, 回答的问题
15, 关注的问题



基准版独有
1, 标签
2, 课程管理 -> 创建/导入 课程
3, 选课

**Comment by arlyxiao** [comment]
Student - 学生方面
两者都有的
1, 问答
2, 基准版导航：个人 = 八中版导航：好友关注
3，动态
4, 教师评价

八中独有的
1, 学生首页
2, 我的课程
3, 收藏的课程
4, 课程作业
5, 文件共享

问答具体一些分支功能
6, 提出的问题
7, 得到的回答
8, 关注的问题


9, 查看公告
10, 我的班级
11, 统计信息



基准版独有
1, 标签
2, 计划
3, 课程 -> 选课

**Comment by fushang318** [comment]
老师部分工作量评估

http://markdown.4ye.me/lWO0zACS/7

**Comment by fushang318** [comment]
学生部分工作量评估
http://markdown.4ye.me/vMsya2Jc/6

**Comment by fushang318** [comment]
# 都有
```
course_zip_exporter.rb
 survey_template.rb
 site_change.rb
 practice_upload.rb
 follow.rb
 course_ware.rb
 survey.rb
 course_ware_reading_delta.rb
 tag.rb
 course_attitude.rb
 report.rb
 weibo_friends.rb
 fill_fields.rb
 user.rb
 activity_membership.rb
 activity.rb
 course_ware_kind_methods.rb
 test_paper_item.rb
 course_read_percent.rb
 category.rb
 media_resource_tip_methods.rb
 yaml_courses_importer.rb
 course.rb
 test_question.rb
 course_zip_importer.rb
 user_opinion.rb
 file_entity_convert_methods.rb
 yaml_courses_exporter.rb
 course_ware_mark.rb
 regex_step.rb
 received_media_resources_info.rb
 weibo_comment.rb
 media_resource_category_methods.rb
 answer_choice.rb
 course_fav.rb
 media_resource.rb
 course_sign.rb
 course_ware_reading_module.rb
 answer_course_ware.rb
 practice_record.rb
 answer.rb
 term_output_reporter.rb
 question_feed_timelime.rb
 javascript_step.rb
 note.rb
 css_step.rb
 course_ware_reading.rb
 answer_vote.rb
 survey_result.rb
 media_resource_crud_methods.rb
 short_message.rb
 java_step.rb
 received_media_resource_info.rb
 media_resource_dynatree_methods.rb
 question_vote.rb
 course_update_status_methods.rb
 step_history.rb
 question_follow.rb
 attrs_config.rb
 course_interactive.rb
 feed.rb
 practice.rb
 file_entity.rb
 fenci.rb
 test_paper.rb
 media_share.rb
 user_feed_stream.rb
 omniauth.rb
 online_record.rb
 course_sign_module.rb
 chapter.rb
 course_ware_mark_module.rb
 question.rb
 announcement.rb
 media_resource_infos_methods.rb
 tag_follow.rb
 ability.rb
 survey_result_item.rb
 test_option.rb
 announcement_user.rb
```


# 八中独有
```
course_teacher.rb
 attachment.rb
 media_resource_download.rb
 group_tree_node_user.rb
 group_tree_node.rb
 select_course.rb
 course_score.rb
 one_course_intent.rb
 user_gender_methods.rb
 group_tree_node_management_kinds.rb
 select_course_intent.rb
 course_intent.rb
 file_entity_download.rb
```


# 基准独有

```
practice_requirement.rb
 team.rb
 practice_attach.rb
 course_subject_course.rb
 course_feed_timelime.rb
 course_subject_follow.rb
 sql_step.rb
 select_course_apply.rb
 course_depend.rb
 course_subject_managership.rb
 course_subject.rb
 team_membership.rb
```

**Comment by fushang318** [comment]
# 课程申报
  基准版模型层已经有相关方法，缺少对应的控制器层和页面

# 作业功能
  1 基准版的作业功能实现，模型关系不够简洁，八种版是在基准版基础上简化过的版本
  2 基准版缺少控制器层和页面

# 文件共享
  基础的文件网盘都有，基准版缺少的是分享这个逻辑的全部实现（实现方式是 id + creator_id encode64,没有却创建任何新持久化模型）

# 问题功能
  基准版模型层只缺少一些简单的查询方法（socpe has_many 之类的），控制器层和页面也没有

# 公告功能
  基准版虽然有公告模型，但是和八中版差别很大，我记得公告功能是重新设计实现过的

# 班级功能
 八中版的班级用的是 GroupTreeNode 模型实现的，基准版并没有相关模型

#计划
  八中版并没有这个页面，但是模型上是有相关实现的

#标签
  基准版的课程标签是用自己封装的 mindpin-simple-tags 实现的，八中版改为了单个分类逻辑

**Comment by fushang318** [comment]
模型差异详细比对

# 八中独有
```
  # 很多模型的附件统一到了这个模型，比如作业布置的附件，提交作业的附件等
  # 八中版才有这个模型，基准版的附件逻辑是各个模型自己重复实现了一个遍
  attachment.rb

  # 文件共享逻辑
  media_resource_download.rb
  file_entity_download.rb

  # 班级逻辑
  group_tree_node_user.rb
  group_tree_node.rb
  group_tree_node_management_kinds.rb

  # 选课逻辑
  select_course_intent.rb
  one_course_intent.rb
  course_intent.rb
  select_course.rb
  # 课程的任课老师（没有起作用，应该是僵尸代码）
  course_teacher.rb
  # 学生给课程打分？（没有起作用，应该是僵尸代码）
  course_score.rb
  # 用户性别（没有起作用，应该是僵尸代码）
  user_gender_methods.rb
```

# 基准独有
```
# 作业的两个附件，八中版简化掉了
practice_requirement.rb
practice_attach.rb

# 班级功能的半成品
team.rb
team_membership.rb
# ...互联网版本的遗留代码
sql_step.rb

# 课程集合
course_subject_managership.rb
course_subject.rb
course_subject_course.rb
course_subject_follow.rb

# 准备用来实现课程前后依赖关系的模型
course_depend.rb
# 没有起作用的僵尸代码
course_feed_timelime.rb
# 做到一半的选课逻辑
select_course_apply.rb
```

**Comment by ben7th** [comment]
第三次 YY 讨论总结：

### 课程方面

1. 课程方面，倾向于基准版，简化考虑。省掉审批环节。
2. 课程内容维护方面，逻辑是基本一致的，除了UI和导航差异。
3. 课程内容浏览方面，逻辑基本一致，除了UI和导航差异。八中版多了课程中心和我的课程。
4. 基准版没有课程收藏的逻辑。
5. 选课需要完全剔除掉。

### 作业方面

1. 基准版是五模型版本，八中版是三模型版本 + 公共附件模型。八中版成熟度高一些，而且有UI。

### 问答

1. 问答方面，逻辑是一致的，八中版的导航项更多一些。

### 文件管理

1. media_resouces + file_entity 模型。基本结构一致。八中多一个下载地址导出（导航上叫文件共享）

### 通知公告

1. 八中版的模型更成熟一些，并且有UI

### 我的班级（用户分组）

1. 八中版有这个功能，而基准版没有。

### 有两个功能是八中版没有的

1. 计划功能（两边都没做完）
2. 课程分类（八中是单级分类，基准版是TAG形式。）

----------------------------------------------------------------------------------------
