### ISSUE TITLE
公告功能设计

### ISSUE THREAD

**Issue by ben7th** [mindpin/beikong-eshare#76]
功能描述：
公告分为两种：系统公告和课程公告。

admin 用户可以创建系统公告，以及在所有课程下创建课程公告
teacher 用户可以在自己任课的课程下创建课程公告
用户可以编辑，修改和删除自己创建的公告，以及设置是否置顶

公告只有一个 Announcement 模型，包括以下属性：
```
title: string 标题
content: text 正文
on_top: boolean 是否置顶，默认值 false
host_id: 关联到的对象的 id，当关联到课程时，值为课程 id
host_type: 关联到的对象的类型，当关联到课程时，值为 Course
# host_id 和 host_type 是多态关联到课程的。
当公告是系统公告时，host_id 为空 host_type 为 System
```

和之前的概念不同，公告不再有收件人。而是所有人都能看到。
软件主页上会有一个公告栏显示系统公告
而每个课程主页上会有一个公告栏显示课程公告
置顶的公告会显示在前面

**Comment by ben7th** [comment]
控制器和view设计：

1. 教师用户可通过：/manage/announcements/new 路径来创建公告。完成该路径的控制器层和view页面。页面上的内容包括一个表单，通过表单能够输入标题和正文，以及通过一个下拉框选择这个公告是系统公告还是课程公告（从当前用户负责的课程里选）

    所谓当前用户负责的课程，指当前用户创建的课程以及当前用户作为负责人的课程。
    我不确定系统内现在是否有这个查询方法，如果没有的话需要补上。
    有两个方法其他地方也会用到，顺便检查一下：

    - 指定一个用户，查询该用户负责的课程，返回数组
    - 指定一个用户和一个课程，判断该用户是否负责这个课程

2. 在 /dashboard 页面增加系统公告的显示

3. 在 /courses/:id/chs 页面增加课程公告的显示

**Comment by arlyxiao** [comment]
指定一个用户，查询该用户负责的课程，返回数组
```
current_user.own_courses
```

指定一个用户和一个课程，判断该用户是否负责这个课程
```
current_user.has_own_course?(course)
```

**Comment by fushang318** [comment]
1 背景图

```
# 获取背景图(如果没有设置过，就返回系统默认的)
SystemConfig.bg_img_url

# 获取 logo图（如果没有设置过，就返回系统默认的）
SystemConfig.logo_img_url

# 设置 背景图
SystemConfig.set_bg_img(file_entity_id)

# 设置 logo图
SystemConfig.set_logo_img(file_entity_id)

# 默认的两个值在 system_config.rb 内修改
# 默认的背景图
SystemConfig::DEFAULT_BG_IMG_URL
# 默认的LOGO图
SystemConfig::DEFAULT_LOGO_IMG_URL
```

2 文件共享点击文件的 tag
```
routes /tags/file/:tag_name
controller disk_controller.rb
action tag_files
view app/views/disk/tag_files.html.haml
```

3 布置作业选择课程的下拉菜单，呈现的课程已经改为任课的所有课程

4 投赞成票的 用户列表
```
answer.voted_up_users
```
