### ISSUE TITLE
3月20号下午发现的一些UI bug

### ISSUE THREAD

**Issue by fushang318** [mindpin/beikong-eshare#78]
1 admin 点左侧导航上的头像进入个人页，页签样式不对

2 admin 上传头像裁切页面，表单显示在了页面最右侧，左右两部分是否可以挨在一起
http://img.teamkn.com/i/tfVVOxjv.png

3 任何用户登陆系统，顶部 输入搜索课程的关键字 搜索按钮点了没反应
http://img.teamkn.com/i/gY4NvjhM.png

4 admin 通过 课程中心，进入课程页（比如 /courses/1/chs）顶部渲染的 view 和其他页面不同
截图对比
http://img.teamkn.com/i/buD8Mbtu.png

http://img.teamkn.com/i/bh6XOXU9.png

5 admin 首页，已经没有 审核的概念了，看截图

http://img.teamkn.com/i/giFKVU75.png

**Comment by arlyxiao** [comment]
公告创建编辑下面的按钮

**Comment by ben7th** [comment]
李飞-2 头像裁切问题，已经改完了

**Comment by ben7th** [comment]
肖少富-1 表单按钮问题，已修改
![image](https://cloud.githubusercontent.com/assets/322486/6752463/baff20c6-cf49-11e4-8ddf-e7744b64bd21.png)

**Comment by ben7th** [comment]
宋亮需要继续改完的内容：

1. 所有角色的登录后首页（快速导航页）需要重做
2. 群组动态页需要重做，要列出用户直接隶属的分组以及每个分组的动态
